// Date: 11/6/2015 7:14:12 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.sythiex.modularpipes.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPipeConnector extends ModelBase
{
	// fields
	ModelRenderer connectorMain;
	ModelRenderer side3;
	ModelRenderer side2;
	ModelRenderer side1;
	ModelRenderer side4;
	
	public ModelPipeConnector()
	{
		textureWidth = 64;
		textureHeight = 32;
		
		connectorMain = new ModelRenderer(this, 0, 0);
		connectorMain.addBox(0F, 0F, 0F, 6, 6, 5);
		connectorMain.setRotationPoint(-3F, 13F, -8F);
		connectorMain.setTextureSize(64, 32);
		connectorMain.mirror = true;
		setRotation(connectorMain, 0F, 0F, 0F);
		side3 = new ModelRenderer(this, 25, 0);
		side3.addBox(0F, 0F, 0F, 1, 4, 6);
		side3.setRotationPoint(-4F, 14F, -8F);
		side3.setTextureSize(64, 32);
		side3.mirror = true;
		setRotation(side3, 0F, 0F, 0F);
		side2 = new ModelRenderer(this, 0, 12);
		side2.addBox(0F, 0F, 0F, 4, 1, 6);
		side2.setRotationPoint(-2F, 12F, -8F);
		side2.setTextureSize(64, 32);
		side2.mirror = true;
		setRotation(side2, 0F, 0F, 0F);
		side1 = new ModelRenderer(this, 25, 11);
		side1.addBox(0F, 0F, 0F, 1, 4, 6);
		side1.setRotationPoint(3F, 14F, -8F);
		side1.setTextureSize(64, 32);
		side1.mirror = true;
		setRotation(side1, 0F, 0F, 0F);
		side4 = new ModelRenderer(this, 0, 20);
		side4.addBox(0F, 0F, 0F, 4, 1, 6);
		side4.setRotationPoint(-2F, 19F, -8F);
		side4.setTextureSize(64, 32);
		side4.mirror = true;
		setRotation(side4, 0F, 0F, 0F);
	}
	
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		connectorMain.render(f5);
		side3.render(f5);
		side2.render(f5);
		side1.render(f5);
		side4.render(f5);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
	
}
