// Date: 11/5/2015 10:53:51 PM
// Template version 1.1
// Java generated by Techne

package com.sythiex.modularpipes.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPipeBase extends ModelBase
{
	// fields
	ModelRenderer center;
	ModelRenderer cap1;
	ModelRenderer cap2;
	ModelRenderer cap3;
	
	public ModelPipeBase()
	{
		textureWidth = 64;
		textureHeight = 32;
		
		center = new ModelRenderer(this, 0, 0);
		center.addBox(0F, 0F, 0F, 6, 6, 6);
		center.setRotationPoint(-3F, 13F, -3F);
		center.setTextureSize(64, 32);
		center.mirror = true;
		setRotation(center, 0F, 0F, 0F);
		cap1 = new ModelRenderer(this, 40, 0);
		cap1.addBox(0F, 0F, 0F, 4, 4, 8);
		cap1.setRotationPoint(-2F, 14F, -4F);
		cap1.setTextureSize(64, 32);
		cap1.mirror = true;
		setRotation(cap1, 0F, 0F, 0F);
		cap2 = new ModelRenderer(this, 0, 24);
		cap2.addBox(0F, 0F, 0F, 8, 4, 4);
		cap2.setRotationPoint(-4F, 14F, -2F);
		cap2.setTextureSize(64, 32);
		cap2.mirror = true;
		setRotation(cap2, 0F, 0F, 0F);
		cap3 = new ModelRenderer(this, 48, 20);
		cap3.addBox(0F, 0F, 0F, 4, 8, 4);
		cap3.setRotationPoint(-2F, 12F, -2F);
		cap3.setTextureSize(64, 32);
		cap3.mirror = true;
		setRotation(cap3, 0F, 0F, 0F);
	}
	
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		center.render(f5);
		cap1.render(f5);
		cap2.render(f5);
		cap3.render(f5);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
	
}
